/**
 * POST /api/projects/[projectId]/reclassify-blocked
 *
 * Backfill: reverts items that were silently auto-excluded by the old
 * "45xx prefix → F" rule, even though the parser had classified them as
 * Tipo C (item agrupado / subcontrato com possível material embutido).
 *
 * Then re-runs the enriched auto-map on every curve of the project so
 * those items get a second chance — matching against the assemblies and
 * canonical descriptions persisted at upload time (migration v5 columns).
 *
 * Idempotent: safe to call multiple times. Only touches item_mappings
 * that were inserted with mapped_by='excluded' (auto-classification),
 * never user-edited rows.
 */
import { NextRequest } from "next/server";
import { getCurrentUser, unauthorized } from "@/lib/server/auth";
import { supabase } from "@/lib/server/supabase";
import { runEnrichedAutoMapForCurve } from "@/lib/server/auto-map";
import { recalculateScenario } from "@/lib/server/calculator";

export const maxDuration = 300;

export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ projectId: string }> }
) {
  let user;
  try {
    user = await getCurrentUser(req);
  } catch {
    return unauthorized();
  }

  const { projectId } = await params;

  const { data: project } = await supabase
    .from("projects")
    .select("id, company_id")
    .eq("id", projectId)
    .eq("company_id", user.company_id)
    .single();

  if (!project) {
    return Response.json({ detail: "Projeto não encontrado" }, { status: 404 });
  }

  const { data: curves } = await supabase
    .from("abc_curves")
    .select("id")
    .eq("project_id", projectId);

  if (!curves || curves.length === 0) {
    return Response.json({ detail: "Nenhuma curva ABC encontrada" }, { status: 404 });
  }

  let revertedTotal = 0;
  let mappedTotal = 0;
  let suggestedTotal = 0;
  let stillBlockedTotal = 0;

  for (const curve of curves) {
    // 1. Get every excluded item in this curve
    const { data: excludedItems } = await supabase
      .from("abc_items")
      .select("id, item_type")
      .eq("abc_curve_id", curve.id)
      .eq("mapping_status", "excluded");

    if (!excludedItems || excludedItems.length === 0) continue;

    const excludedIds = excludedItems.map((i) => i.id as string);
    const typeById = new Map<string, string>(
      excludedItems.map((i) => [i.id as string, i.item_type as string]),
    );

    // 2. Of those, keep only the ones whose mapping is algorithmic. New
    //    auto-classifications mark mapped_by='auto_excluded'; legacy rows
    //    (written before that flag existed) carry the canonical
    //    auto-justification text generated by autoExclusionReason /
    //    laborOnlyExclusionReason. User-typed manual exclusions miss both
    //    markers.
    const { data: mappings } = await supabase
      .from("item_mappings")
      .select("abc_item_id, mapped_by, exclusion_justification")
      .in("abc_item_id", excludedIds);

    const autoMarkers = [
      "classificação automática por código de custo",
      "decomposto pelo Relatório Proof",
    ];
    const autoExcludedIds = (mappings ?? [])
      .filter((m) => {
        if (m.mapped_by === "auto_excluded") return true;
        const j = String(m.exclusion_justification ?? "");
        return autoMarkers.some((marker) => j.includes(marker));
      })
      .map((m) => m.abc_item_id as string);

    if (autoExcludedIds.length === 0) continue;

    // 3. Restore parser-C items to `blocked`. Items the parser classified
    //    otherwise (A/B/D/E/F) but that the prefix override forced into
    //    excluded go to `pending` so they re-enter the main match loop.
    const cIds: string[] = [];
    const pendingIds: string[] = [];
    for (const id of autoExcludedIds) {
      if (typeById.get(id) === "C") cIds.push(id);
      else pendingIds.push(id);
    }

    // 4. Delete the auto-exclusion mappings (never touches user rows).
    await supabase
      .from("item_mappings")
      .delete()
      .in("abc_item_id", autoExcludedIds);

    if (cIds.length > 0) {
      await supabase
        .from("abc_items")
        .update({ mapping_status: "blocked" })
        .in("id", cIds);
    }
    if (pendingIds.length > 0) {
      await supabase
        .from("abc_items")
        .update({ mapping_status: "pending" })
        .in("id", pendingIds);
    }

    revertedTotal += autoExcludedIds.length;

    // 4. Re-run enriched auto-map on this curve. Pass empty enrichment
    //    inputs — the v5 persisted columns (canonical_description,
    //    assemblies) already provide the hints for the main loop.
    const result = await runEnrichedAutoMapForCurve(
      curve.id as string,
      user.company_id,
      {}
    );
    mappedTotal += result.auto_mapped;
    suggestedTotal += result.suggested;
    stillBlockedTotal += result.pending;
  }

  // 5. Recalculate every scenario in the project so emission totals
  //    reflect the rescued items.
  const { data: scenarios } = await supabase
    .from("scenarios")
    .select("id")
    .eq("project_id", projectId);

  for (const s of scenarios ?? []) {
    try {
      await recalculateScenario(s.id as string);
    } catch (e) {
      console.warn("[reclassify-blocked] recalc failed for scenario", s.id, e);
    }
  }

  return Response.json({
    reverted: revertedTotal,
    auto_mapped: mappedTotal,
    suggested: suggestedTotal,
    still_blocked: stillBlockedTotal,
    scenarios_recalculated: scenarios?.length ?? 0,
  });
}
